### ISSUE TITLE
Incorrect ballance

### ISSUE THREAD

**Issue by thewarlok666** [wishhhmaster/CoinTNet#1]
More than 1 way to skin a cat... Here's the issue I was reffering to.

Cheers

![05072017-01 incorrect balance](https://cloud.githubusercontent.com/assets/6732394/2915964/dc7d420c-d6b4-11e3-9a89-3e4c3bc365ad.png)

**Comment by wishhhmaster** [comment]
Closed by 1214e90b2a0de20f808ea2a56245d679c7068490
