### ISSUE TITLE
Update (Duplicate of #1)

### ISSUE THREAD

**Issue by thewarlok666** [wishhhmaster/CoinTNet#2]
This from updated release.zip

![image](https://cloud.githubusercontent.com/assets/6732394/2916490/d8485166-d6bb-11e3-823c-efd8bcf8f5ea.png)

**Comment by wishhhmaster** [comment]
Duplicate of #1, closed by commit 1214e90b2a0de20f808ea2a56245d679c7068490

**Comment by thewarlok666** [comment]
test post please ignore
