### ISSUE TITLE
Display incorrect

### ISSUE THREAD

**Issue by thewarlok666** [wishhhmaster/CoinTNet#3]
Three issues here.
1. RED Major, Repeatable. An open sell order also shows as available balance. There is indeed an sell order, and is displayed correctly, however there is no more Moon available. The only Moon I have is in the sell order and should not show as available. Error.log shows nothing. Possibly an API issue?
2. BLUE I have date range set for one week, yet only showing two days worth of data . Clicking refresh has no affect. LOT-LTC also does this. On other coin pairs (LTC-BTC), it shows correctly. Setting to one months worth has no affect for this coin, yet on other coins pulls differing amounts of data. Some a week. Some a day, and others a month. Seems to have now pattern that I can tell yet. Again, Error.log shows nothing. Possibly API issues?
3. YELLOW High, low @ top of form only showing 0.00. Many pairs do this, other show 'correctly'.

![050102014-01 incorrect balance](https://cloud.githubusercontent.com/assets/6732394/2937265/66613510-d894-11e3-8556-7fb02a2a3bfd.png)

**Comment by thewarlok666** [comment]
Update. When another sell order (Moon) is pending, available balance displays sum of pending sell orders. Sorry, no screen shot of that one. After cancelling one order, Available balance then displays correctly. This is with Moon/LTC pair. Previous issue with LOT/BTC pair remains only displays sum of pending sell orders (RED). And not actual balance (ORANGE).
![05-12-2014-01 incorrect balances](https://cloud.githubusercontent.com/assets/6732394/2950274/beb91de2-da18-11e3-914d-bc91d5f9130d.png)

**Comment by wishhhmaster** [comment]
1. Was closed as part of issue #1 
2. Depending on the exchange and currency pair selected, there is more or less data available. For most of the pairs traded on Cryptsy, only data from cryptsy's available, which corresponds to the most recent 1000 trades. For other exchanges, data is retrieved from bitcoincharts or bitcoinwisdom if available. I will clarify the 'documentation' to reflect that.

3.Cryptsy does not seem to provide a complete fast ticker, so 24 hours lows/highs cannot be retrieved
