### ISSUE TITLE
Fields not populating

### ISSUE THREAD

**Issue by thewarlok666** [wishhhmaster/CoinTNet#5]
First. RED. last seems to correctly populate but High,Low does not. API?

Second BLUE. Sell. Clicking on 'AV Balance' correctly populates 'Amount' field, yet clicking on 'Highest Bid' only populates Sell price with 0.00. Fee and total fields do not change. Code and API?

Third. GREEN. Clicking 'Av Balance' does not populate amount field. Code?

Switching to a different coin pair yields the same results noted above.

![0 0 0 4a fields not populating](https://cloud.githubusercontent.com/assets/6732394/2988019/daff233c-dc54-11e3-9f67-9a69e4a1af01.png)

**Comment by thewarlok666** [comment]
Any word on these (green, blue) yet?

**Comment by wishhhmaster** [comment]
Red: Cryptsy does not seem to provide a 'fast' ticker indicating the 24h low/high prices. They do return in in some method, but not from the one I use to get the latest price. I'll need to modify which API calls are made to get a proper ticker, but it might make the ticker slower

Blue: Clicking on the available balance will only fill the amount fill if the Buy price is >0

Green: for an identical reason to the red issue, highest bid/lowest ask are not returned from the API. Once again, I'll make different calls
